kind: pipeline
type: docker
name: 盘古应用框架


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


environment:
  GOPROXY: https://goproxy.cn


steps:
  - name: 拉代码
    image: plugins/git
    pull: if-not-exists

  - name: 生成文档
    image: node
    pull: if-not-exists
    commands:
      - cd doc
      - yarn install
      - yarn docs:build

  - name: 部署到腾讯云
    image: storezhang/cos
    pull: if-not-exists
    settings:
      secretId: AKIDKRDlxzLDxUnMK4MMdqpw87Zn46tWx5xe
      secretKey:
        from_secret: cos_secret_key
      folder: doc/dist


volumes:
  - name: deps
    temp: { }
