kind: pipeline
type: docker
name: 发布


clone:
  disable: true


environment:
  CHANGELOG_TAG_OUTPUT: CHANGELOG.tag.md


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      compress:
        enabled: false

  - name: 改变
    image: ccr.ccs.tencentyun.com/dronestock/changelog
    when:
      event:
        - tag
    settings:
      output: $${CHANGELOG_TAG_OUTPUT}
      tag: $${DRONE_TAG}

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/github
    when:
      event:
        - tag
    environment:
      TOKEN:
        from_secret: token_github
    settings:
      release:
        tag: $${DRONE_TAG}
        token: $${TOKEN}
        body: exe:file("$${CHANGELOG_TAG_OUTPUT}")

  - name: 文档
    image: ccr.ccs.tencentyun.com/dronestock/node
    settings:
      folder: doc

  - name: 部署
    image: ccr.ccs.tencentyun.com/dronestock/cos
    settings:
      folder: doc/dist
      secret_id:
        from_secret: secret_id_cos
      secret_key:
        from_secret: secret_key_cos
      base_url: https://pangu-1253228583.cos.ap-chengdu.myqcloud.com


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
