kind: pipeline
type: docker
name: 盘古应用框架


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


environment:
  GOPROXY: https://goproxy.cn


steps:
  - name: 拉代码
    image: plugins/git
    pull: if-not-exists

  - name: 生成文档
    image: node
    pull: if-not-exists
    commands:
      - cd doc
      - yarn docs:build


volumes:
  - name: deps
    temp: { }
