kind: pipeline
type: docker
name: 盘古


clone:
  disable: true


steps:
  - name: 通知
    image: lizheming/drone-wechat
    corpid:
      from_secret: corpid_wxwork
    corp_secret:
      from_secret: corp_secret_wxwork_drone
    agent_id: 1000002
    to_party: 10853102415923281
    title: Test
    message: "Build Number"
    msg_url: ${DRONE_BUILD_LINK}
    btn_txt: btn

  - name: 代码
    image: dronestock/git

  - name: 编译
    image: pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      compress:
        enabled: false

  - name: 文档
    image: dronestock/node
    settings:
      folder: doc

  - name: 部署
    image: dronestock/cos
    settings:
      folder: doc/dist
      secret_id:
        from_secret: secret_id_cos
      secret_key:
        from_secret: secret_key_cos
      base_url: https://pangu-1253228583.cos.ap-chengdu.myqcloud.com


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
