kind: pipeline
type: docker
name: 盘古应用框架


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


environment:
  GOPROXY: https://goproxy.cn


steps:
  - name: 拉代码
    image: plugins/git
    pull: if-not-exists

  - name: 部署到腾讯云
    image: storezhang/cos
    settings:
      secretId:
        from_secret: cos_secret_id
      secretKey:
        from_secret: cos_secret_key
      baseUrl: https://pangu-1253228583.cos.ap-chengdu.myqcloud.com
      folder: doc/dist


volumes:
  - name: deps
    temp: { }
